language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/dinosaure/ocaml-travisci-skeleton/master/.travis-docgen.sh
script: bash -ex .travis-opam.sh
sudo: true
env:
  global:
    - PINS="eqaf.dev:https://github.com/dinosaure/eqaf.git"
  matrix:
  - PACKAGE="digestif" OCAML_VERSION=4.03 TESTS=true
  - PACKAGE="digestif" OCAML_VERSION=4.04 TESTS=true
  - PACKAGE="digestif" OCAML_VERSION=4.05 TESTS=true
  - PACKAGE="digestif" OCAML_VERSION=4.06 TESTS=true
  - PACKAGE="digestif" OCAML_VERSION=4.07 TESTS=true

  - PACKAGE="digestif" OCAML_VERSION=4.03
    PINS="eqaf.dev:https://github.com/dinosaure/eqaf.git digestif-test-c:test"
    EXTRA_DEPS="digestif-test-c"
  - PACKAGE="digestif" OCAML_VERSION=4.04
    PINS="eqaf.dev:https://github.com/dinosaure/eqaf.git digestif-test-c:test"
    EXTRA_DEPS="digestif-test-c"
  - PACKAGE="digestif" OCAML_VERSION=4.05
    PINS="eqaf.dev:https://github.com/dinosaure/eqaf.git digestif-test-c:test"
    EXTRA_DEPS="digestif-test-c"
  - PACKAGE="digestif" OCAML_VERSION=4.06
    PINS="eqaf.dev:https://github.com/dinosaure/eqaf.git digestif-test-c:test"
    EXTRA_DEPS="digestif-test-c"
  - PACKAGE="digestif" OCAML_VERSION=4.07
    PINS="eqaf.dev:https://github.com/dinosaure/eqaf.git digestif-test-c:test"
    EXTRA_DEPS="digestif-test-c"

  - PACKAGE="digestif" OCAML_VERSION=4.03
    PINS="eqaf.dev:https://github.com/dinosaure/eqaf.git digestif-test-ocaml:test"
    EXTRA_DEPS="digestif-test-ocaml"
  - PACKAGE="digestif" OCAML_VERSION=4.04
    PINS="eqaf.dev:https://github.com/dinosaure/eqaf.git digestif-test-ocaml:test"
    EXTRA_DEPS="digestif-test-ocaml"
  - PACKAGE="digestif" OCAML_VERSION=4.05
    PINS="eqaf.dev:https://github.com/dinosaure/eqaf.git digestif-test-ocaml:test"
    EXTRA_DEPS="digestif-test-ocaml"
  - PACKAGE="digestif" OCAML_VERSION=4.06
    PINS="eqaf.dev:https://github.com/dinosaure/eqaf.git digestif-test-ocaml:test"
    EXTRA_DEPS="digestif-test-ocaml"
  - PACKAGE="digestif" OCAML_VERSION=4.07
    PINS="eqaf.dev:https://github.com/dinosaure/eqaf.git digestif-test-ocaml:test"
    EXTRA_DEPS="digestif-test-ocaml"
